### ISSUE TITLE
What`s wrong with my site?

### ISSUE THREAD

**Issue by amaroc** [AwesomeMobileApps/kikder-dating-swipe-app#3]
Hi! I had install kikder by your instruction on server.
I can register, signin but i cant do anything else, like add photo, change my description, etc.

Also i tried login by "admin" email but i have same interface, there is no link on anything. 

Can you look?  And give advice what i did wrong?

PHP 5.6.35-1+ubuntu16.04.1+deb.sury.org+1 (cli)
apache2 
mysql  Ver 14.14 Distrib 5.7.24, for Linux
https://bit.ly/2SxcZJm

**Comment by pH-7** [comment]
It's a simple webapp :) There is no admin panel (and even, no need to).
And profile photo is taken from Kik's user account.

**Comment by pH-7** [comment]
If you want something much more powerful with everything (and full admin panel), maybe you should use [ph7Builder](https://github.com/pH7Software/pH7-Social-Dating-CMS)
